apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-ds
spec:
  host: rte.cluster
  subsets:
  - name: version1
    labels:
      app: frontend
      version: "1.0"