apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.service.name }}
  namespace: {{ .Values.svc.namespace.name }}
  labels:
    app: frontend-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.svc.service.port }}
      targetPort: {{ .Values.svc.deployment.containerPort}}
  selector:
    app: frontend-svc