# Default values for product-service-v1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

svc:
  version: "1.0"
  namespace:
    name: frontend
  service:
    name: frontend-svc
    port: 3001
  serviceAccount:
    name: frontend-sa
  deployment:
    replicaCount: 1
    containerPort: 80
    image:
      repository: bpcontaineracr.azurecr.io/frontend
      tag: "1.0"
      pullPolicy: Always
  vs:
    name: frontend-vs
