apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.svc.serviceAccount.name }}
  namespace: {{ .Values.svc.namespace.name }}
  labels:
    account: product
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.db.serviceAccount.name }}
  namespace: {{ .Values.db.namespace.name }}
  labels:
    account: product-db