# Default values for product-service-v1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: "1.0"

namespace:
  name: product-service

service:
  name: product-svc
  port: 7001

serviceAccount:
  name: product-sa

deployment:
  replicaCount: 1
  containerPort: 5002
  runAsUser: 10001
  image:
    repository: bpcontaineracr.azurecr.io/product-service
    tag: "1.0"
    pullPolicy: IfNotPresent


