apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.svc.namespace.name }}
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.db.namespace.name }}
  labels:
    istio-injection: enabled