apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: product
    service: product
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: product
