apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.svc.vs.name }}
  namespace: {{ .Values.svc.namespace.name }}
spec:
  hosts:
  - "rte.cluster"
  gateways:
  - istio-system/store-gateway
  http:
  - route:
    - destination:
        host: {{ .Values.svc.service.name }}
        port:
          number: {{ .Values.svc.service.port }}
