apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.service.name }}
  namespace: {{ .Values.svc.namespace.name }}
  labels:
    app: review-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.svc.service.port }}
      targetPort: {{ .Values.svc.deployment.containerPort}}
  selector:
    app: review-svc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  namespace: {{ .Values.db.namespace.name }}
  labels:
    app: review-db
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.deployment.containerPort}}
  selector:
    app: review-db