# Default values for product-service-v1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

svc:
  version: "1.0"
  namespace:
    name: review-service
  service:
    name: review-svc
    port: 4001
  serviceAccount:
    name: review-sa
  deployment:
    replicaCount: 1
    containerPort: 5002
    runAsUser: 10001
    image:
      repository: bpcontaineracr.azurecr.io/review-service
      tag: "1.0"
      pullPolicy: Always
  vs:
    name: review-vs


db:
  version: "1.0"
  namespace:
    name: review-db
  service:
    name: db
    port: 5001
  serviceAccount:
    name: review-db-sa
  deployment:
    replicaCount: 1
    containerPort: 27017
    image:
      repository: bpcontaineracr.azurecr.io/review-db
      tag: "1.0"
      pullPolicy: Always