apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: review-ds
spec:
  host: api.rte.cluster
  subsets:
  - name: version1
    labels:
      app: review
      version: "1.0"